### ISSUE TITLE
Consider these changes

### ISSUE THREAD

**Issue by StrangeEcho** [cheekysim/Williepillar#3]
1. Be consistent consistent with your code and using a formatter like black and possibly try to line your code up with pythons [PEP8](https://peps.python.org/pep-0008/) style guide. It will make your code look a lot nicer, cleanlier, and readable. 
2. Code adjustments
- [Greetings event listener](https://github.com/cheekysim/Williepillar/blob/69ddfff68d598d1a9ff6d3ed4e1a9173eb3501cc/cogs/greetings.py#L14) This event will not work. `discord.TextChannel` has no method called `.respond`. You would need to access the `.send` method that attaches on too all `discord.Messageable` objects. As well as a small code adjustment that can be done. When doing logical statements, it is redundant to use `is not None` in your case you can just do `if channel:` and it will apply the same effect.
- It would be beneficial for you as well as anyone who views this repository to use type-hints and type-annotations. It eliminates confusion on what something could be and helps you IDE's intellisense provide appropriate code completion for you.
For example:
    - Type-Hint: `async def commandname(self, ctx: commands.Context, ...)` when using the ctx arg from this command you will be able to see all the possible attributes and methods ctx has. Overall, it makes your life a lot easier.\n
    - Type-Annotations: `def method(...) -> str` type-annotations are just like type hints but they apply to a function or method's return type. This of course benefits your intellisense. As seen here in my example, this annotates that the method or function will return a string. 
3. Some small notes, personally I wouldnt use json for config. Json is meant for states not config, data storage, etc. Consider using toml, yaml, or even a .env. All would be inherently better than a json file.
4. 99% of the imports in the [music](https://github.com/cheekysim/Williepillar/blob/main/cogs/music.py) cog is redundant
5. With [this](https://github.com/cheekysim/Williepillar/blob/69ddfff68d598d1a9ff6d3ed4e1a9173eb3501cc/cogs/general.py#L20) piece of code here. It is completely unnecessary to be doing what you're doing. All that information can be accessed when you use `datetime.datetime.strftime()`
6. [This](https://github.com/cheekysim/Williepillar/commit/75b61f2045ddf2b71f69fe5346de403f72e98d59) commit isn't really that well put. I have no idea why you need `self` in that instance. There is no OOP to be found in that file at all meaning that there is no instance of a class that needs to be accessed at all. Generally, all the code in this module is ugly and mostly bad practice. You break the bare exception clause multiple times. Be specific when handling errors.

**Comment by Yat-o** [comment]
also dont use camelCase in python. Its disgusting. We have snake_case for a reason.

**Comment by cheekysim** [comment]
Hey, thanks for all the input it is appreciated,
1. Yes you may not like how my code is formatted but I do, you also have to consider 2 people are working on this with completley different coding styles so there will always be some differences
2.
The greetings.py file is very old ( we started by building off an old bot i started making ) and has not been changed since we started this project as we have not got to it yet.

With the hints and annotations, thank you neither of us knew that was a thing and it seems useful,

Json works just fine for me thanks

Devil is working on the music command and it will all be cleaned up when it actually works

Thank you i did not know strftime existed and it seems a lot easier

The reason it has self and ctx is so we can automate the footer that we want on every embed. So instead of typing out the whole footer, you just add self and ctx which is much more convenient

If you dont like the embed.py file then gimme some suggestions on how to do it better since this was all i could think of.

Thank you :)

**Comment by StrangeEcho** [comment]
To start, i understand adding ctx for footer automation. However, you still don't need self. Whatever you think self is doing there is not actually what it does. self is in reference to the class you're in. As far as that embed function, there is no class. It's just a function in the global namespace. when you use the function and pass in self such as in the games.py file. You are passing an instance of the Cog class that you don't use.

**Comment by cheekysim** [comment]
Thank you, I've looked over it and removed self from the embed module
